# Python for Neuroscientists 6: Assignment

In [1]:
import numpy as np
import pandas as pd

## 1. Read in the data frames
Begin by reading in the data frames saved under 'population_wb.csv' and 'gdp.csv' and assigning them to `population` and `gdp`, respectively.

*Hint* Take a look at the section on loading data frames in the original notebooks.

In [3]:
population = pd.read_csv('population_wb.csv')
gdp = pd.read_csv('gdp.csv')

population

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,470898870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,33933611.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1806279.0
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5315351.0,5393034.0,5473671.0,5556767.0,5641598.0,5727745.0,...,24473176.0,25147112.0,25823488.0,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0,30490639.0
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,17099836.0,17524533.0,17965733.0,18423157.0,18896303.0,19384838.0,...,52832659.0,53687125.0,54544184.0,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0,60041996.0
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3070780.0,3164330.0,3260645.0,3360099.0,3463211.0,3570466.0,...,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,18920657.0
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3776679.0,3905038.0,4039209.0,4178726.0,4322854.0,4471178.0,...,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,15092171.0

In [4]:
gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129059e+10,2.180847e+10,2.370702e+10,2.821004e+10,2.611879e+10,2.968217e+10,...,9.730430e+11,9.839370e+11,1.003680e+12,9.242530e+11,8.823550e+11,1.020650e+12,9.910220e+11,9.975340e+11,9.216460e+11,1.082100e+12
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,...,7.275700e+11,8.207930e+11,8.649900e+11,7.607340e+11,6.905460e+11,6.837490e+11,7.416900e+11,7.945430e+11,7.844460e+11,8.358080e+11
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249980e+11,1.334020e+11,1.372440e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.048420e+11,3.879350e+11,3.354420e+11,4.199460e+11
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10

## 2. Melt the data frames
Both data frames are saved in a wide format. Use the `melt` function (similar to the way we have used it in class) to bring them into a long format, where each row corresponds to a country in one particular year. For this purpose, you need to specify every column that you don't want to turn into an observation as a list for the argument `id_vars`. The name of your variable should be `'year'` and the name of the corresponding value should be `'value'`.

*Hint* Take a look at the `melt` command in the original notebook and consider how you have to change its arguments.

In [6]:
population_tidy = population.melt(
    id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
    var_name='year',
    value_name='value'
)
population_tidy

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
0,Aruba,ABW,"Population, total",SP.POP.TOTL,1960,54208.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1960,130836765.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,1960,8996967.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,1960,96396419.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,1960,5454938.0
...,...,...,...,...,...,...
16487,Kosovo,XKX,"Population, total",SP.POP.TOTL,2021,1806279.0
16488,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,2021,30490639.0
16489,South Africa,ZAF,"Population, total",SP.POP.TOTL,2021,60041996.0
16490,Zambia,ZMB,"Population, total",SP.POP.TOTL,2021,18920657.0
16491,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,2021,15092171.0

In [7]:
gdp_tidy = gdp.melt(
    id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],
    var_name='year',
    value_name='value'
)
gdp_tidy

,Country Name,Country Code,Indicator Name,Indicator Code,year,value
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,1960,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,1960,2.129059e+10
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,1960,5.377778e+08
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1960,1.040414e+10
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,1960,NaN
...,...,...,...,...,...,...
16487,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,2021,9.007159e+09
16488,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,2021,2.106169e+10
16489,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,2021,4.199460e+11
16490,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,2021,2.120306e+10
16491,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,2021,2.621773e+10

## 3. (Advanced.) Concatenate the data frames
The function `pd.concat` takes in a list of data frames and concatenates them. Concatenate `population` and `gdp` and assign the name `df` to be.

In [ ]:
pd.concat

In [49]:
df = pd.concat([population,gdp])
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population, total",SP.POP.TOTL,5.420800e+04,5.543400e+04,5.623400e+04,5.669900e+04,5.702900e+04,5.735700e+04,...,1.025650e+05,1.031650e+05,1.037760e+05,1.043390e+05,1.048650e+05,1.053610e+05,1.058460e+05,1.063100e+05,1.067660e+05,1.071950e+05
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.308368e+08,1.341598e+08,1.376146e+08,1.412020e+08,1.449202e+08,1.487700e+08,...,5.474829e+08,5.626016e+08,5.780754e+08,5.938718e+08,6.099789e+08,6.263929e+08,6.430901e+08,6.600463e+08,6.772433e+08,6.946651e+08
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8.996967e+06,9.169406e+06,9.351442e+06,9.543200e+06,9.744772e+06,9.956318e+06,...,3.116138e+07,3.226959e+07,3.337080e+07,3.441360e+07,3.538303e+07,3.629611e+07,3.717192e+07,3.804176e+07,3.892834e+07,3.983543e+07
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,9.639642e+07,9.840722e+07,1.005070e+08,1.026913e+08,1.049535e+08,1.072899e+08,...,3.702430e+08,3.804379e+08,3.908830e+08,4.015867e+08,4.125513e+08,4.237699e+08,4.352294e+08,4.469116e+08,4.588035e+08,4.708989e+08
4,Angola,AGO,"Population, total",SP.POP.TOTL,5.454938e+06,5.531451e+06,5.608499e+06,5.679409e+06,5.734995e+06,5.770573e+06,...,2.510792e+07,2.601579e+07,2.694177e+07,2.788438e+07,2.884248e+07,2.981677e+07,3.080979e+07,3.182530e+07,3.286627e+07,3.393361e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.048420e+11,3.879350e+11,3.354420e+11,4.199460e+11
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10

## 4. (Advanced.) Pivot the data frame
The result `df` is an example of a dataframe that is too long. Here population and GDP should be different variables, yet they are specified as different observations. The method `df.pivot` can help you fix that. Pivot takes a particular column and uses each of its value as a new column. To be able to apply `pivot`, first drop the column `'Indicator Code'`:

In [50]:
new_df = df.drop(columns = 'Indicator Code')
new_df

,Country Name,Country Code,Indicator Name,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population, total",5.420800e+04,5.543400e+04,5.623400e+04,5.669900e+04,5.702900e+04,5.735700e+04,5.770200e+04,...,1.025650e+05,1.031650e+05,1.037760e+05,1.043390e+05,1.048650e+05,1.053610e+05,1.058460e+05,1.063100e+05,1.067660e+05,1.071950e+05
1,Africa Eastern and Southern,AFE,"Population, total",1.308368e+08,1.341598e+08,1.376146e+08,1.412020e+08,1.449202e+08,1.487700e+08,1.527527e+08,...,5.474829e+08,5.626016e+08,5.780754e+08,5.938718e+08,6.099789e+08,6.263929e+08,6.430901e+08,6.600463e+08,6.772433e+08,6.946651e+08
2,Afghanistan,AFG,"Population, total",8.996967e+06,9.169406e+06,9.351442e+06,9.543200e+06,9.744772e+06,9.956318e+06,1.017484e+07,...,3.116138e+07,3.226959e+07,3.337080e+07,3.441360e+07,3.538303e+07,3.629611e+07,3.717192e+07,3.804176e+07,3.892834e+07,3.983543e+07
3,Africa Western and Central,AFW,"Population, total",9.639642e+07,9.840722e+07,1.005070e+08,1.026913e+08,1.049535e+08,1.072899e+08,1.097018e+08,...,3.702430e+08,3.804379e+08,3.908830e+08,4.015867e+08,4.125513e+08,4.237699e+08,4.352294e+08,4.469116e+08,4.588035e+08,4.708989e+08
4,Angola,AGO,"Population, total",5.454938e+06,5.531451e+06,5.608499e+06,5.679409e+06,5.734995e+06,5.770573e+06,5.781305e+06,...,2.510792e+07,2.601579e+07,2.694177e+07,2.788438e+07,2.884248e+07,2.981677e+07,3.080979e+07,3.182530e+07,3.286627e+07,3.393361e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09
262,"Yemen, Rep.",YEM,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10
263,South Africa,ZAF,GDP (current US$),8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.048420e+11,3.879350e+11,3.354420e+11,4.199460e+11
264,Zambia,ZMB,GDP (current US$),7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10
265,Zimbabwe,ZWE,GDP (current US$),1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10

Now use pivot to tidy the data frame. The argument `index` should specify all columns you want to keep. `columns`, as a single string should specify the column you want to use to define your new columns. This should by the column specifying the particular indicator. Finally, `values`, as a single string, should specify the column that should fill those new columns.

In [51]:
new_df.pivot(index=['Country Name','Country Code'], columns='Indicator Name')

                                                      1960                    \
Indicator Name                           GDP (current US$) Population, total
Country Name                Country Code
Afghanistan                 AFG               5.377778e+08      8.996967e+06
Africa Eastern and Southern AFE               2.129059e+10      1.308368e+08
Africa Western and Central  AFW               1.040414e+10      9.639642e+07
Albania                     ALB                        NaN      1.608800e+06
Algeria                     DZA               2.723593e+09      1.105786e+07
...                                                    ...               ...
West Bank and Gaza          PSE                        NaN               NaN
World                       WLD               1.392050e+12      3.032156e+09
Yemen, Rep.                 YEM                        NaN      5.315351e+06
Zambia                      ZMB               7.130000e+08      3.070780e+06
Zimbabwe                    ZWE               1.052990e+09      3.776679e+06

                                                      1961                    \
Indicator Name                           GDP (current US$) Population, total
Country Name                Country Code
Afghanistan                 AFG               5.488889e+08      9.169406e+06
Africa Eastern and Southern AFE               2.180847e+10      1.341598e+08
Africa Western and Central  AFW               1.112789e+10      9.840722e+07
Albania                     ALB                        NaN      1.659800e+06
Algeria                     DZA               2.434727e+09      1.133634e+07
...                                                    ...               ...
West Bank and Gaza          PSE                        NaN               NaN
World                       WLD               1.448390e+12      3.071596e+09
Yemen, Rep.                 YEM                        NaN      5.393034e+06
Zambia                      ZMB               6.962857e+08      3.164330e+06
Zimbabwe                    ZWE               1.096647e+09      3.905038e+06

                                                      1962                    \
Indicator Name                           GDP (current US$) Population, total
Country Name                Country Code
Afghanistan                 AFG               5.466667e+08      9.351442e+06
Africa Eastern and Southern AFE               2.370702e+10      1.376146e+08
Africa Western and Central  AFW               1.194319e+10      1.005070e+08
Albania                     ALB                        NaN      1.711319e+06
Algeria                     DZA               2.001428e+09      1.161983e+07
...                                                    ...               ...
West Bank and Gaza          PSE                        NaN               NaN
World                       WLD               1.550300e+12      3.124561e+09
Yemen, Rep.                 YEM                        NaN      5.473671e+06
Zambia                      ZMB               6.931429e+08      3.260645e+06
Zimbabwe                    ZWE               1.117602e+09      4.039209e+06

                                                      1963                    \
Indicator Name                           GDP (current US$) Population, total
Country Name                Country Code
Afghanistan                 AFG               7.511112e+08      9.543200e+06
Africa Eastern and Southern AFE               2.821004e+10      1.412020e+08
Africa Western and Central  AFW               1.267633e+10      1.026913e+08
Albania                     ALB                        NaN      1.762621e+06
Algeria                     DZA               2.702960e+09      1.191280e+07
...                                                    ...               ...
West Bank and Gaza          PSE                        NaN               NaN
World                       WLD               1.671350e+12      3.189656e+09
Yemen, Rep.                 YEM                        NaN      5.556767e+06
Zambia                      ZMB               7.187143e+08      3.360099e+06
Zimbabwe                    ZWE               1.159512e+09      4.178726e+06

                                                      1964                    \
Indicator Name                           GDP (current US$) Population, total
Country Name                Country Code
Afghanistan                 AFG               8.000000e+08      9.744772e+06
Africa Eastern and Southern AFE               2.611879e+10      1.449202e+08
Africa Western and Central  AFW               1.383837e+10      1.049535e+08
Albania                     ALB                        NaN      1.814135e+06
Algeria                     DZA               2.909293e+09      1.222168e+07
...                                                    ...               ...
West Bank and Gaza          PSE                        NaN               NaN
World                       WLD               1.830000e+12      3.255146e+09
Yemen, Rep.                 YEM                        NaN      5.641598e+06
Zambia                      ZMB               8.394286e+08      3.463211e+06
Zimbabwe                    ZWE               1.217138e+09      4.322854e+06

                                          ...              2017  \
Indicator Name                            ... GDP (current US$)
Country Name                Country Code  ...
Afghanistan                 AFG           ...      1.875347e+10
Africa Eastern and Southern AFE           ...      1.020650e+12
Africa Western and Central  AFW           ...      6.837490e+11
Albania                     ALB           ...      1.301969e+10
Algeria                     DZA           ...      1.700970e+11
...                                       ...               ...
West Bank and Gaza          PSE           ...      1.612800e+10
World                       WLD           ...      8.140400e+13
Yemen, Rep.                 YEM           ...      2.684223e+10
Zambia                      ZMB           ...      2.587360e+10
Zimbabwe                    ZWE           ...      1.758489e+10

                                                                        2018  \
Indicator Name                           Population, total GDP (current US$)
Country Name                Country Code
Afghanistan                 AFG               3.629611e+07      1.805323e+10
Africa Eastern and Southern AFE               6.263929e+08      9.910220e+11
Africa Western and Central  AFW               4.237699e+08      7.416900e+11
Albania                     ALB               2.873457e+06      1.515643e+10
Algeria                     DZA               4.138917e+07      1.749110e+11
...                                                    ...               ...
West Bank and Gaza          PSE               4.454805e+06      1.627660e+10
World                       WLD               7.519371e+09      8.641300e+13
Yemen, Rep.                 YEM               2.783481e+07      2.160616e+10
Zambia                      ZMB               1.685361e+07      2.631159e+10
Zimbabwe                    ZWE               1.423660e+07      1.811554e+10

                                                                        2019  \
Indicator Name                           Population, total GDP (current US$)
Country Name                Country Code
Afghanistan                 AFG               3.717192e+07      1.879945e+10
Africa Eastern and Southern AFE               6.430901e+08      9.975340e+11
Africa Western and Central  AFW               4.352294e+08      7.945430e+11
Albania                     ALB               2.866376e+06      1.540183e+10
Algeria                     DZA               4.222842e+07      1.717670e+11
...                                                    ...               ...
West Bank and Gaza          PSE               4.569087e+06      1.713350e+10
World                       WLD               7.602716e+09      8.765290e+13
Yemen, Rep.                 YEM               2.849868e+07      2.188761e+10
Zambia                      ZMB               1.735171e+07      2.330867e+10
Zimbabwe                    ZWE               1.443881e+07      1.928429e+10

                                                                        2020  \
Indicator Name                           Population, total GDP (current US$)
Country Name                Country Code
Afghanistan                 AFG               3.804176e+07      2.011614e+10
Africa Eastern and Southern AFE               6.600463e+08      9.216460e+11
Africa Western and Central  AFW               4.469116e+08      7.844460e+11
Albania                     ALB               2.854191e+06      1.513187e+10
Algeria                     DZA               4.305305e+07      1.450090e+11
...                                                    ...               ...
West Bank and Gaza          PSE               4.685306e+06      1.553170e+10
World                       WLD               7.683806e+09      8.490680e+13
Yemen, Rep.                 YEM               2.916192e+07      1.884051e+10
Zambia                      ZMB               1.786103e+07      1.811063e+10
Zimbabwe                    ZWE               1.464547e+07      1.805117e+10

                                                                        2021  \
Indicator Name                           Population, total GDP (current US$)
Country Name                Country Code
Afghanistan                 AFG               3.892834e+07               NaN
Africa Eastern and Southern AFE               6.772433e+08      1.082100e+12
Africa Western and Central  AFW               4.588035e+08      8.358080e+11
Albania                     ALB               2.837849e+06      1.826004e+10
Algeria                     DZA               4.385104e+07      1.679830e+11
...                                                    ...               ...
West Bank and Gaza          PSE               4.803269e+06      1.803680e+10
World                       WLD               7.763933e+09      9.610010e+13
Yemen, Rep.                 YEM               2.982597e+07      2.106169e+10
Zambia                      ZMB               1.838396e+07      2.120306e+10
Zimbabwe                    ZWE               1.486293e+07      2.621773e+10


Indicator Name                           Population, total
Country Name                Country Code
Afghanistan                 AFG               3.983543e+07
Africa Eastern and Southern AFE               6.946651e+08
Africa Western and Central  AFW               4.708989e+08
Albania                     ALB               2.811666e+06
Algeria                     DZA               4.461663e+07
...                                                    ...
West Bank and Gaza          PSE               4.922749e+06
World                       WLD               7.836631e+09
Yemen, Rep.                 YEM               3.049064e+07
Zambia                      ZMB               1.892066e+07
Zimbabwe                    ZWE               1.509217e+07

[266 rows x 124 columns]

The resulting dataframe will have certain columns saved as rownames again. Use the `reset_index` method to correct this.

In [52]:
new_new_df=new_df.reset_index()
new_new_df

,index,Country Name,Country Code,Indicator Name,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,0,Aruba,ABW,"Population, total",5.420800e+04,5.543400e+04,5.623400e+04,5.669900e+04,5.702900e+04,5.735700e+04,...,1.025650e+05,1.031650e+05,1.037760e+05,1.043390e+05,1.048650e+05,1.053610e+05,1.058460e+05,1.063100e+05,1.067660e+05,1.071950e+05
1,1,Africa Eastern and Southern,AFE,"Population, total",1.308368e+08,1.341598e+08,1.376146e+08,1.412020e+08,1.449202e+08,1.487700e+08,...,5.474829e+08,5.626016e+08,5.780754e+08,5.938718e+08,6.099789e+08,6.263929e+08,6.430901e+08,6.600463e+08,6.772433e+08,6.946651e+08
2,2,Afghanistan,AFG,"Population, total",8.996967e+06,9.169406e+06,9.351442e+06,9.543200e+06,9.744772e+06,9.956318e+06,...,3.116138e+07,3.226959e+07,3.337080e+07,3.441360e+07,3.538303e+07,3.629611e+07,3.717192e+07,3.804176e+07,3.892834e+07,3.983543e+07
3,3,Africa Western and Central,AFW,"Population, total",9.639642e+07,9.840722e+07,1.005070e+08,1.026913e+08,1.049535e+08,1.072899e+08,...,3.702430e+08,3.804379e+08,3.908830e+08,4.015867e+08,4.125513e+08,4.237699e+08,4.352294e+08,4.469116e+08,4.588035e+08,4.708989e+08
4,4,Angola,AGO,"Population, total",5.454938e+06,5.531451e+06,5.608499e+06,5.679409e+06,5.734995e+06,5.770573e+06,...,2.510792e+07,2.601579e+07,2.694177e+07,2.788438e+07,2.884248e+07,2.981677e+07,3.080979e+07,3.182530e+07,3.286627e+07,3.393361e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,261,Kosovo,XKX,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09
528,262,"Yemen, Rep.",YEM,GDP (current US$),NaN,NaN,NaN,NaN,NaN,NaN,...,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10
529,263,South Africa,ZAF,GDP (current US$),8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.344010e+11,4.008860e+11,3.811990e+11,3.467100e+11,3.235860e+11,3.814490e+11,4.048420e+11,3.879350e+11,3.354420e+11,4.199460e+11
530,264,Zambia,ZMB,GDP (current US$),7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10
531,265,Zimbabwe,ZWE,GDP (current US$),1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10